export const FETCH_ALBUMS_START = "FETCH_ALBUMS_START";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAILED = "FETCH_ALBUMS_FAILED";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_VALID = "AUTH_VALID";
export const AUTH_INVALID = "AUTH_INVALID";
export const AUTH_LOGOUT = "AUTH_LOGOUT";