export const FETCH_ALBUMS_START = "FETCH_ALBUMS_START";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAILED = "FETCH_ALBUMS_FAILED";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_VALID = "AUTH_VALID";
export const AUTH_INVALID = "AUTH_INVALID";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_ALBUM_START = "FETCH_ALBUM_START";
export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const FETCH_ALBUM_FAILED = "FETCH_ALBUM_FAILED";

export const FETCH_SONGS_START = "FETCH_SONGS_START";
export const FETCH_SONGS_SUCCESS = "FETCH_SONGS_SUCCESS";
export const FETCH_SONGS_FAILED = "FETCH_SONGS_FAILED";